### ISSUE TITLE
[Feature request] Add an ability to resize headers

### ISSUE THREAD

**Issue by y9san9** [kepano/obsidian-minimal-settings#10]
First of all, thanks for your work, I've checked all white themes without exceptions and this one is the only nice to me. 

My problem is that I am doing my homework in obsidian and headers look pretty nice in every note except these notes. 
 
<img width="1440" alt="Снимок экрана 2021-11-04 в 19 26 54" src="https://user-images.githubusercontent.com/46930374/140379229-d5dada3d-382c-4216-b33b-57425ecabece.png">

For me, it's not critical that I will have like normal headers in every note, so it will look better in these notes with homework :)

**Comment by kepano** [comment]
You can do this via the Style Settings plugin or use a snippet to define the heading size variables

**Comment by SamAdams51** [comment]
Hi kepano,
I enjoy the Minimal Theme for quite a while and there is only the header sizes that I find to be to small. In order to adjust this, I use the „Style Settings“ plug-in. However, it leads to different header sizes in edit and preview mode. Therefore it is just a workaround for me but not a good one. Unfortunately I don’t know how to write a css-snippet to change the header sizes. Could you consider to put the ability to change the header sizes into the „Minimal Theme Settings“ plug-in?

**Comment by davidculley** [comment]
@SamAdams51 You can create a CSS snippet like so:

In the Obsidian settings, go to _Appearance_ and there you'll find a header called _CSS Snippets_. To its right, there is a directory symbol titled "Open snippets folder". Clicking it will open a folder in Windows Explorer/macOS Finder.

There, create a new file and name it, for example, `header-size.css` (the name doesn't really matter so long it ends with `.css`). Open that file with your favorite text editor and paste these lines into it:

```css
:root {
  --h1:1.125em;
  --h2:1em;
  --h3:1em;
  --h4:0.90em;
  --h5:0.85em;
  --h6:0.85em;
}
```

These are the original values for the headers you can find in the [source code](https://github.com/kepano/obsidian-minimal/blob/master/obsidian.css#L174-L179) of the theme.

Save that file you created, but keep it open. You will need it again in a moment. Back in the Obsidian settings, "Reload snippets" and activate the toggle of your file named `header-size`.

Now change the sizes in the file `header-size.css` to bigger numbers until you like what you see.

Hope this helps.

**Comment by SamAdams51** [comment]
Hi David,

Many thanks for your help. The snippet works almost as you said. All headings now have the size I like. There is only one thing so:

Header 3 looks very different in preview mode than in edit mode (see attached screen shots). It looks like the header 3 is not emphasised
in preview mode. Is this caused by the code of the Minimal Theme or do you have another explanation for that?

The only plug-ins I have activated are:
System Dark Mode
Minimal Theme Settings

And there are no other snippets in the snippet folder than the „Header-Size.css“ file.

I also selected different fonts in the Minimal Theme Settings plug-in but no change.

Best regards
Helmut
