### ISSUE TITLE
[Feature request] Add an ability to add table borders

### ISSUE THREAD

**Issue by y9san9** [kepano/obsidian-minimal-settings#11]
Sorry for russian here 🙈. I store my scheduling in obsidian, so I made it in html table and the only thing I don't like here is the borders. It was better when the table had borders, so I would like to have a setting for this case.

<img width="1440" alt="Снимок экрана 2021-11-04 в 19 39 13" src="https://user-images.githubusercontent.com/46930374/140381371-b223430e-7eef-408c-848a-cdaf0ef2d605.png">

**Comment by kepano** [comment]
Have you looked into creating a CSS snippet? This should be just a couple lines of code, something like

```
table { border:1px solid var(--background-modifier-border; }
```

You can use `table tr` or `table td` depending on which element you want a border around

You can also get help on the forum and Discord with small customizations like that
https://forum.obsidian.md/t/getting-comfortable-with-obsidian-css/133

**Comment by y9san9** [comment]
Okay, this one looks nice, but how can I center text in td tags? I'm not very good at css, so sorry for like a noob question :(

<img width="850" alt="Снимок экрана 2021-11-04 в 19 58 54" src="https://user-images.githubusercontent.com/46930374/140384641-c8f1f33c-0c54-487e-bb7e-1467137d5227.png">

<img width="666" alt="Снимок экрана 2021-11-04 в 19 59 04" src="https://user-images.githubusercontent.com/46930374/140384669-3f0fd0a7-3263-4043-936d-a5f3a3683397.png">

**Comment by kepano** [comment]
I would recommend asking this question on the Obsidian forum or Discord because it's not really related to this plugin.

There are a few solutions to this, one would be [in the markup of your file](https://stackoverflow.com/questions/24127507/is-it-possible-to-center-tables-in-a-markdown-file), another would be as a CSS snippet that applies to all tables, or use YAML to define classes that will only apply to a specific file

The basic code is as follows, but you'll likely need to add more specific selectors
`table td { text-align: center;}`

**Comment by y9san9** [comment]
Okay, further questions I will ask on the forum, thanks a lot for your help and this theme, looks pretty good!
