### ISSUE TITLE
light mode background contrast: high contrast setting persists after disabling the plugin (until restart of Obsidian)

### ISSUE THREAD

**Issue by danieltomasz** [kepano/obsidian-minimal-settings#64]
**Before you open a bug report**
Disable plugins and snippets that could be causing a conflict. Update to the latest versions of the following, and restart Obsidian:

- Minimal Theme 6.3.11 
- Obsidian 1.3.5
- Minimal Theme Settings plugin 6.3.1
- Contextual Typography plugin No

**Confirm that the bug is not present when Minimal theme is off**
Yes

**Describe the bug**
A clear and concise description of the bug

Obsidian minimal setting are override other setting when I am using other themes, for example Things

**To reproduce**
Provide steps to reproduce the behavior

- Install obsidian minimal settings
- Install Minimal theme
 - set light mode background contrast to high contrast
 - Change theme to other theme (fot example things)
 - The sidebar has black/dark accents
- this black accent is active even after deactivating minimal setting, only restart of Obsidian helps

**Expected behavior**
A clear and concise description of what you expected to happen

the  minimal settings will be not active when I change the theme (vanilla obsidian doesnt have this problem)

**Screenshots**
If applicable, add screenshots to help explain your problem

![image](https://github.com/kepano/obsidian-minimal-settings/assets/7980381/dd67461e-a119-4907-ae8d-44c361748721)

**Debug info (required):**
Paste your debug info below, which can be accessed in Obsidian with Ctrl/Cmd-P, enter "Show debug info", and click "Copy to clipboard"

**Comment by danieltomasz** [comment]
Is is also possible to set the high contrast when the theme set is not minimal, which gives weird results sometimes
![image](https://github.com/kepano/obsidian-minimal-settings/assets/7980381/f013f954-d55e-43a1-acac-2f2bc172d8c5)

**Comment by kepano** [comment]
Minimal Theme Settings is intended to be used with Minimal so this can be solved by disabling the plugin.

**Comment by danieltomasz** [comment]
@kepano disabling the plugin doesn't work, only restart of Obsidian remove the active "high contrast" css effect which might be considered as bug

**Comment by isaacfreeman** [comment]
> Minimal Theme Settings is intended to be used with Minimal so this can be solved by disabling the plugin.

This is true enough in principle, but in practice many people will have Minimal Theme Settings installed when they try other themes. If they have `High Contrast` set, then other themes will render incorrectly, and it's not obvious to a typical user that Minimal Theme Settings would affect some other theme entirely. This isn't an abstract concern: I've personally just spent several days going back and forth with a user to figure out why my theme was rendering poorly for them. I was lucky to get a patient and understanding user who was willing to post screenshots and debug info to a forum thread, or I'd never have known!

In the short term, I've patched my own theme to override the Minimal Theme Settings behaviour by replacing
```css
.theme-light {
 ...
}
```css
with 
```css
.theme-light,
.theme-light .theme-dark {
  ...
}
```
which looks weird, but gets the job done. However, my theme happens to be in active development right now, whereas I suspect there are many other affected themes that don't get updates as frequently, and whose authors may not be aware of the problem.

Longer term, could I ask that Minimal Theme Settings be adjusted so that the `High Contrast` setting doesn't break other themes if users happen to leave it on? My suggestion would be that instead of applying `.theme-dark` to the ribbon and sidebar, it could use a new class name specific to Minimal (something like `.minimal-subtheme-dark`, say). Then have the Minimal CSS apply the same styles to `.theme-dark` and `.minimal-subtheme-dark` (similarly to what I've done). Perhaps you can see a better approach, but I hope that's useful.

**Comment by kepano** [comment]
Fixed in 8.0.0

**Comment by danieltomasz** [comment]
With 8.0.0 I can reproduce the behaviour: I set `light mode background contrast` to `High contrast`, and the sidebar stays in dark mode when I switch to other themes, both with the Minimal Settings Plugin   turned off and turned on

**Comment by kepano** [comment]
Oops, good catch. Try 8.0.1

**Comment by danieltomasz** [comment]
Zipped source code doesn't seem to be updated from 8.0.0, Obsidian  doesnt see new version

**Comment by kepano** [comment]
You should see it now

**Comment by danieltomasz** [comment]
yes, it works now!
